# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    contentunit_repository:
        class: AppBundle\Entity\ContentunitRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Contentunit

    app.form.type.banner_image:
        class: AppBundle\Form\Type\BannerImageType
        tags:
            - { name: form.type, alias: app_banner_image }


    validator.unique.banner_image:
        class: AppBundle\Validator\Constraints\BannerImageValidator
        arguments:
            - "@contentunit_repository"
        tags:
            - { name: validator.constraint_validator, alias: banner_image_validator }


